### ISSUE TITLE
Fresh install, can't browse to service

### ISSUE THREAD

**Issue by mig5** [TrsstProject/trsst#25]
I have downloaded the standalone .jar onto a 64-bit VM running Ubuntu 14.04. I installed Java 7 with 'apt-get install default-jdk'.

I started the service with:

java -jar trsst-client-0.2-SNAPSHOT-standalone.jar serve --port 8181 --clear

I put an Nginx proxy in front of the service using a commercial SSL certificate on port 443. (I wasn't able to connect to the service directly with or without --clear, as modern browser seem to forbid the self-signed cert here)

Now when I visit the URL via the Nginx proxy I just get 404s (screenshot attached) when I hit the main URL or at https://example.com/feed. What am I doing wrong? It's my 4th attempt to get Trsst up and running and I'm a bit frustrated :) 

I also wasn't able to build from source per the README on Ubuntu 14.04 due to 'Could not find artifact com.oracle:javafx:jar:2.2 at specified path'.

The only message that appears on the request to /feed (and it only appears once) is:

Aug 25, 2014 6:11:14 PM org.apache.axiom.util.stax.dialect.StAXDialectDetector detectDialect
WARNING: Unable to determine dialect of the StAX implementation at jar:file:/root/trsst-client-0.2-SNAPSHOT-standalone.jar!/

![screen shot 2014-08-26 at 8 13 10 am](https://cloud.githubusercontent.com/assets/99173/4037560/b456682a-2ca5-11e4-95df-1706b49650a2.png)

**Comment by mig5** [comment]
The pull seems to work when I request an account (it fetches down from home.trsst.com) so it seems otherwise that the server works OK, just that it has no frontpage/assets to display. I think this might be deliberate, still learning the code..

**Comment by mmpowers** [comment]
Correct: you need to specify the --gui option to serve the HTML/JS client.

**Comment by mig5** [comment]
Thank you, it was --api that I apparently needed in order to serve it in a standard web browser :) Got it working now.
