### ISSUE TITLE
Where is the vowel ?

### ISSUE THREAD

**Issue by nikoss** [TrsstProject/trsst#3]
... in the name, that is ... where is the vowel? ... is this done on purpose, or have you not giving it any thought? ... do you think that the name is more catchy this way? 

just my 2cents...

**Comment by mmpowers** [comment]
Appreciate your concern, but it's kind of a love-it-or-hate-it kind of thing.  As such, I'm going to have to mark this as not-a-bug.  I hope this won't dissuade you from staying involved!

**Comment by sarciszewski** [comment]
tRSSt
RSS = Really Simple Syndication

**Comment by vinipsmaker** [comment]
And according to an [old version of the FAQ](https://github.com/TrsstProject/trsst/wiki/Frequently-Asked-Questions/6e8f8266fce4f5b4d3deb29e515dff8b902f71db#wiki-how-do-you-pronounce-trsst), the name come from RSS and tweet. I think it's a very acceptable proposal.

And I think (my personal point of view) it's a great name.
