### ISSUE TITLE
Trsst site loads forever on firefox

### ISSUE THREAD

**Issue by vinipsmaker** [TrsstProject/trsst#4]
The [trsst site](http://trsst.com/) takes forever to load on the latest firefox version (27.0.1).

It works fine on Chromium.

**Comment by mmpowers** [comment]
Correct, it's not loading at all on FFX due to a JS error, but probably an easy fix.  We're only really testing on webkit at the moment.

**Comment by mmpowers** [comment]
OK, this should be fixed with the latest commit -- please verify, thanks.

**Comment by vinipsmaker** [comment]
Confirmed
