### ISSUE TITLE
Mailing list please?

### ISSUE THREAD

**Issue by vinipsmaker** [TrsstProject/trsst#7]
I aknowledge that the project's goal is to create a new communication media and it'd be appropriate for discussions happen in this very media, but it's not ready.

I'd like to ask more about the recent [hashcash](https://github.com/TrsstProject/trsst/commit/8249eeccd4115554fa83ea5a8dda4e9627525c3a#diff-d800dd40c14264d1ffdb5bd53dedf292R220) feature, but it's annoying to register a "bug" just to do so.

**Comment by c33s** [comment]
would also be possible to use one "bug" as mailing list. after subscribing here, everyone would get the email and the issue also acts as mailinglist archive.

**Comment by vinipsmaker** [comment]
@c33s the problem with this approach as a "mailing list" is that you can no longer use email filters to ignore some threads while following others. Everything would pretty much get "noised" together.

**Comment by mmpowers** [comment]
OK, here you go: https://groups.google.com/forum/#!aboutgroup/trsst-dev

Could this be the first issue closed proper?

**Comment by vinipsmaker** [comment]
> Could this be the first issue closed proper?

By "proper" you mean that the user reporting should close it? Okay, I can do that.

**Comment by mmpowers** [comment]
Just meant it was an issue I actually fixed. :)
