### ISSUE TITLE
Try harder to get an item's timestamp in TrsstAdapter.java

### ISSUE THREAD

**Issue by ghost** [TrsstProject/trsst#8]
At the moment, the Trsst server throws lots of NullPointerExceptions at TrsstAdapter.java:964, where the item's timestamp is converted to a long, in order to calculate a unique item id.

Experimentally, I had some success in using entry.getPublished() as a secondary source for the cases in which entry.getUpdated() returns null. However, there seem to be many feeds for the elements of which both methods return null.

In order not to be unable to convert as many feed items as now, there should be more attempts to get a date for a feed item (most of the items I have looked at have a pubDate tag, but I don't know how or whether Abdera handles that).

**Comment by mmpowers** [comment]
Made some changes here a while ago -- can you confirm a fix or are you still having problems with your feed?  Thanks.

**Comment by ghost** [comment]
seems to be fixed. closing.
